# Generated by Django 4.1.4 on 2023-01-04 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads')),
            ],
        ),
    ]
